\ words for timer 
\ GTCCR – General Timer/Counter Control Register
\ Timer/counter 0 : 8 bit
\ TCCR0A  $24 ($44) Timer/Counter Control Register A
\ TCCR0B  $25 ($45) Timer/Counter Control Register B
\ TCNT0   $26 ($46) Timer/Counter 
\ OCR0A   $27 ($47) Output Compare Register A
\ OCR0B   $28 ($48) Output Compare Register B
\ TIFR0   $15 ($35) Timer/Counter 0 Interrupt Flag Register
\ TIMSK0  ($6E) Timer/Counter Interrupt Mask Register

\ number of milliseconds since last clear
var ms
\ ISR for counting ms ticks generated by Timer 0
:isr T0ms
  ms 1+!
;isr

&32 isr T0ms

\ setup timer 0 for ~1ms timer counter overflow interrupt
: initT0
  0 ms !
\ use prescaler of 64
\ timer 0 will generate an overflow event 976.56 times in a second
  %011 $45 c!
\ setup timer in normal count mode and normal port mode
  %0 $44 c!
\ clear overflow flag by setting the flag
  %1 $35 c!
\ enable timer overflow interupt
  %1 $6E c!
;
